### ISSUE TITLE
UAT All X-Axis & Y-Axis Range Zooms

### ISSUE THREAD

**Issue by npaszty** [insightsengineering/teal.goshawk#133]
using CRP as assay
range zoom defaults to slider
Boxplot Tick marks don't look right
![image](https://user-images.githubusercontent.com/40777373/160936614-8ea1db27-6d16-4d67-8399-1d806e412fcc.png)

changing range zoom by toggle to inputs and setting max to max+10 results in expected 0 to max+10 range axis.
but when toggle back to slider the slider value range returns to 0 to max but the plot still displays 0 to max+10. need to slide to max-1 to trigger reactivity and now the axis range is 0 to max-1.

**Comment by npaszty** [comment]
@gogonzo 

there is still something odd going on here. using the study app we have been testing new version with it looks like the plot is okay but the slider seems to get displayed with incorrect tick marks right out of the gate.

![image](https://github.com/user-attachments/assets/f74dda6c-8b33-4aef-b764-f003455858bc)

**Comment by donyunardi** [comment]
Might have something to do with how steps are generated/updated in teal.goshawk:
https://github.com/insightsengineering/teal.goshawk/blob/main/R/utils-keep_range_slider_updated.r

## Acceptance Criteria:
* Slider tick should show appropriate steps and not repetitive

**Comment by m7pr** [comment]
Confirming that I was able to reproduce with `?` example

<details><summary>The code</summary>

```r
# Example using ADaM structure analysis dataset.
data <- teal_data()
data <- within(data, {
  library(dplyr)
  library(nestcolor)
  library(stringr)
  
  # use non-exported function from goshawk
  h_identify_loq_values <- getFromNamespace("h_identify_loq_values", "goshawk")
  
  # original ARM value = dose value
  arm_mapping <- list(
    "A: Drug X" = "150mg QD",
    "B: Placebo" = "Placebo",
    "C: Combination" = "Combination"
  )
  set.seed(1)
  ADSL <- rADSL
  ADLB <- rADLB
  var_labels <- lapply(ADLB, function(x) attributes(x)$label)
  ADLB <- ADLB %>%
    mutate(
      AVISITCD = case_when(
        AVISIT == "SCREENING" ~ "SCR",
        AVISIT == "BASELINE" ~ "BL",
        grepl("WEEK", AVISIT) ~ paste("W", str_extract(AVISIT, "(?<=(WEEK ))[0-9]+")),
        TRUE ~ as.character(NA)
      ),
      AVISITCDN = case_when(
        AVISITCD == "SCR" ~ -2,
        AVISITCD == "BL" ~ 0,
        grepl("W", AVISITCD) ~ as.numeric(gsub("[^0-9]*", "", AVISITCD)),
        TRUE ~ as.numeric(NA)
      ),
      AVISITCD = factor(AVISITCD) %>% reorder(AVISITCDN),
      TRTORD = case_when(
        ARMCD == "ARM C" ~ 1,
        ARMCD == "ARM B" ~ 2,
        ARMCD == "ARM A" ~ 3
      ),
      ARM = as.character(arm_mapping[match(ARM, names(arm_mapping))]),
      ARM = factor(ARM) %>% reorder(TRTORD),
      ACTARM = as.character(arm_mapping[match(ACTARM, names(arm_mapping))]),
      ACTARM = factor(ACTARM) %>% reorder(TRTORD),
      ANRLO = 50,
      ANRHI = 75
    ) %>%
    rowwise() %>%
    group_by(PARAMCD) %>%
    mutate(LBSTRESC = ifelse(
      USUBJID %in% sample(USUBJID, 1, replace = TRUE),
      paste("<", round(runif(1, min = 25, max = 30))), LBSTRESC
    )) %>%
    mutate(LBSTRESC = ifelse(
      USUBJID %in% sample(USUBJID, 1, replace = TRUE),
      paste(">", round(runif(1, min = 70, max = 75))), LBSTRESC
    )) %>%
    ungroup()
  
  attr(ADLB[["ARM"]], "label") <- var_labels[["ARM"]]
  attr(ADLB[["ACTARM"]], "label") <- var_labels[["ACTARM"]]
  attr(ADLB[["ANRLO"]], "label") <- "Analysis Normal Range Lower Limit"
  attr(ADLB[["ANRHI"]], "label") <- "Analysis Normal Range Upper Limit"
  
  # add LLOQ and ULOQ variables
  ALB_LOQS <- h_identify_loq_values(ADLB, "LOQFL")
  ADLB <- left_join(ADLB, ALB_LOQS, by = "PARAM")
})

datanames <- c("ADSL", "ADLB")
datanames(data) <- datanames


join_keys(data) <- default_cdisc_join_keys[datanames]

app <- init(
  data = data,
  modules = modules(
    tm_g_gh_boxplot(
      label = "Box Plot",
      dataname = "ADLB",
      param_var = "PARAMCD",
      param = choices_selected(c("ALT", "CRP", "IGA"), "ALT"),
      yaxis_var = choices_selected(c("AVAL", "BASE", "CHG"), "AVAL"),
      xaxis_var = choices_selected(c("ACTARM", "ARM", "AVISITCD", "STUDYID"), "ARM"),
      facet_var = choices_selected(c("ACTARM", "ARM", "AVISITCD", "SEX"), "AVISITCD"),
      trt_group = choices_selected(c("ARM", "ACTARM"), "ARM"),
      loq_legend = TRUE,
      rotate_xlab = FALSE,
      hline_arb = c(60, 55),
      hline_arb_color = c("grey", "red"),
      hline_arb_label = c("default_hori_A", "default_hori_B"),
      hline_vars = c("ANRHI", "ANRLO", "ULOQN", "LLOQN"),
      hline_vars_colors = c("pink", "brown", "purple", "black"),
    )
  )
)
if (interactive()) {
  shinyApp(app$ui, app$server)
}

```

</details>

# State 1 - app initialized

<img width="470" alt="image" src="https://github.com/user-attachments/assets/fc66d0cd-f8b2-4443-baa6-a2a6cd68265a">


# State 2 - slider toggled to numeric input

<img width="410" alt="image" src="https://github.com/user-attachments/assets/27c8bd4c-406a-4ab0-a9e7-2842b213f5d4">


# Stage 3 - slider toggled to numeric input and extended and plot changed

<img width="386" alt="image" src="https://github.com/user-attachments/assets/bad43dc0-1a8f-4dfc-83e8-e11fd722664e">


# Stage 4 - back to slider, slider shows 0-55, plot uses 0-65 - no reactivity triggered

<img width="399" alt="image" src="https://github.com/user-attachments/assets/31579254-5e48-45b9-95ec-e1628013cef8">

**Comment by m7pr** [comment]
`tm_g_gh_boxplot` uses `toggle_slider_ui`

```r
 toggle_slider_ui(
    ns("yrange_scale"),
    label = "Y-Axis Range Zoom",
    min = -1000000,
    max = 1000000,
    value = c(-1000000, 1000000)
  )
````

for `Y-Axis Range Zoom` so the work probably needs to be done around `toggle_slider_ui` and `toggle_slider_server`
