### ISSUE TITLE
UAT Lineplot Legend Overwrite

### ISSUE THREAD

**Issue by npaszty** [insightsengineering/teal.goshawk#134]
minor issue with legend overwrite of arbitrary horizontal line(s)
![image](https://user-images.githubusercontent.com/40777373/160940408-532d61fb-bb06-462c-829a-3968bdf0bddd.png)

**Comment by donyunardi** [comment]
I ran the example for lineplot and I can't reproduce the bug:

![image](https://user-images.githubusercontent.com/8597300/192948976-9707ed45-8e39-42b9-b17b-3b9bc7958593.png)

All I did is changing the Value of Arbitrary Horizontal Lines's to "Horizontal Line 1, Horizontal Line 2"

@npaszty Did I miss anything additional step to trigger the bug?

**Comment by npaszty** [comment]
@donyunardi 

whoa, this is an old issue looks like. I can't reproduce from 2022_06_09 so I guess it was fixed.
