### ISSUE TITLE
lineplot

### ISSUE THREAD

**Issue by npaszty** [insightsengineering/teal.goshawk#155]
need to be able to change the default setting of relative_height UI element in app.R.
 it's not a function arg so can it be made one or can I get at it a different way at the app.R level?
would like to be able to control default `value =` argument
```
div(
        sliderInput(
          ns("relative_height"),
          div(
            "Relative height of plot to table(s)",
            title =
              paste(
                "The larger the value selected the greater the size of the plot relative\nto",
                "the size of the tables. Note the units of this slider are arbitrary.\nTo",
                "change the total size of the plot and table(s)\nuse",
                "the plot resizing controls available at the top right of the plot."
              ),
            icon("info-circle")
          ),
          min = 500,
          max = 5000,
          step = 50,
          value = 1000,
          ticks = FALSE
        )
```

**Comment by npaszty** [comment]
@pawelru 
just circling back on this to see if it can be done in the next release.

**Comment by pawelru** [comment]
@kumamiao @donyunardi @gogonzo please make a call here

**Comment by gogonzo** [comment]
Hi @npaszty ,
in goshawk we use `plot_with_settings` to control independently the size of the displayed plot. Also in goshawk functions we have a `plot_height` which is overridden by the `plot_with_settings`. Change of the `lineplot(..., plot_height)` is completely unpredictable at this moment so I think default values are not possible to influence in the current design. 
I'll put this on board to see what we can do.

**Comment by nikolas-burkoff** [comment]
@gogonzo this is a different option to the plot_with_settings which is specific to the lineplot

![image](https://user-images.githubusercontent.com/15201933/179202413-7e4ba1e6-7e53-4368-ad7c-8d137800a29f.png)

So I think this can be done quite easily so I'll give it a go

**Comment by npaszty** [comment]
thanks @nikolas-burkoff
