### ISSUE TITLE
Deprecate scatterplot module 

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.goshawk#168]
### Feature description

Also deprecate from goshawk see https://github.com/insightsengineering/teal.goshawk/pull/163#issuecomment-1176442104

FYI @npaszty 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by npaszty** [comment]
@nikolas-burkoff 
thanks. I'm good with this

**Comment by gogonzo** [comment]
Pplease make sure if goshawk::g_scatterplot should also be deprecated.

**Comment by npaszty** [comment]
@gogonzo 
the scatter plot functionality is a subset of the correlation plot functionality. so for my part I don't use the goshawk function or the associated teal module anymore.
not sure to what degree others might but the deprecation is for upcoming releases and expect for older releases it would persist.
