### ISSUE TITLE
Warnings in goshawk app

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.goshawk#169]
![image](https://user-images.githubusercontent.com/15201933/177797669-40ff9eef-224a-4ced-9241-2b8eb2b78a3d.png)

The chunks eval warnings can be ignored as the chunks implementation is about to change; however, the others should be investigated

Try running the longitudinal sample app (or individual modules) to reproduce

**Comment by junlueZH** [comment]
I am not able to reproduce the type coercion warnings on either the longitudinal sample app or the oxygen sample apps.

I just get the chunks warnings:

![Screen Shot 2022-07-11 at 12 32 43 AM](https://user-images.githubusercontent.com/12874196/178195413-4307e5b9-695d-444e-bc2c-f619455c1e68.png)

**Comment by nikolas-burkoff** [comment]
Have you tried on R 4.2?
