### ISSUE TITLE
Review `tgoshawk` documentation before release

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.goshawk#216]
### Summary
Related with insightsengineering/nestdevs-tasks#25
In preparation to release, we need to review/assess all documentation in the package. 

### Acceptance Criteria
* Review roxygen examples on all functions
  * [x] Test examples
  * [x] If it's using chunk, update to `qenv`.
* Review vignettes on these topics only:
  * [x] Review any content around `qenv`
  * [x] Review any content around `chunks` (i.e. make sure the right language around deprecation)
  * [x] Review any content around shinyvalidate
* redo the content of WORDLIST
  * [x] For instruction on how to do this, visit https://github.com/insightsengineering/coredev-tasks/issues/235 https://github.com/insightsengineering/teal.goshawk/pull/221
* [x] Update NEWS
* [x] Update README (if applicable)
* [x] Review DESCRIPTION file (i.e check dependency versions, etc)
  * [x] Be sure to update teal.code dependency to be >= 0.3.0

**Comment by npaszty** [comment]
@donyunardi 
please add me to review when the proposed changes to bullet 1, 2, and 5 are pushed.

**Comment by m7pr** [comment]
Hey @gogonzo if you started on this one, you may want to know that WORDLIST reduction was made in here https://github.com/insightsengineering/teal.goshawk/pull/221
