### ISSUE TITLE
[Bug]: nest_longitudinal_dev disconnected on Line Plot module

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.goshawk#265]
### What happened?

A bug happened!

The nest_longitudinal_dev app disconnected on Line Plot module.

Steps to reproduce:
1. Go to [nest_longitudinal_dev](https://genentech.shinyapps.io/nest_longitudinal_dev/)
2. Click on Visualization
3. Click on Line Plot
4. The app will get disconnected

![image](https://github.com/insightsengineering/teal.gallery/assets/8597300/71f59cf9-7df2-4cab-8899-a5dae5799766)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by gogonzo** [comment]
Fixed here

https://github.com/insightsengineering/teal.goshawk/pull/270
https://github.com/insightsengineering/goshawk/pull/219
