### ISSUE TITLE
Line Plot & Spaghetti Plot: X-Axis Label

### ISSUE THREAD

**Issue by npaszty** [insightsengineering/teal.goshawk#289]
### Feature description

the x-axis label is AVISITCD which isn't actually correct as far as the values displayed. 

because of the tick mark functionlity in this module, user can change tick label to whatever they want however it is based on AVISITCD. 

the x-axis label should be changed to "Analysis Visit" instead of displaying the name of the variable as AVISITCD.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by m7pr** [comment]
Part of the enhancement is provided in `goshawk`. https://github.com/insightsengineering/goshawk/pull/250
I will also raise a separate PR for `teal.goshawk`

**Comment by m7pr** [comment]
PR in teal.goshawk https://github.com/insightsengineering/teal.goshawk/pull/320

**Comment by m7pr** [comment]
Closed with https://github.com/insightsengineering/goshawk/pull/259
