### ISSUE TITLE
Show R Code

### ISSUE THREAD

**Issue by npaszty** [insightsengineering/teal.goshawk#291]
### Feature description

  - [ ]  boxplot: does not include print(p) and print (tbl) lines so user has to run the p and tbl object to view
  - [ ] density distribution: does not include print(p) and print (tbl) lines so user has to run the p and tbl object to view

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by m7pr** [comment]
Fix was provided in this PR https://github.com/insightsengineering/teal.goshawk/pull/293
