### ISSUE TITLE
[Question]: Should `Show R Code` return code for the table for `tm_g_gh_correlationplot`

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.goshawk#292]
Currently this module only returns the code for the plot. Should it also return the code for the table?

**Comment by m7pr** [comment]
CC @npaszty

**Comment by npaszty** [comment]
@m7pr 

there is no table in correlation plot unless you are refering to the selected data points object. that is only populated when user brushes the plot data points.

can that even be included in the show R code?

**Comment by npaszty** [comment]
@m7pr 

set to low-priority as it isn't a blocker for now to needing to tag and release.

**Comment by donyunardi** [comment]
I don't believe we can add the Selected Data Points object of the brushed data as I can't think of how we would add that to the `teal_data` object. If there's no apparent business need on this, let's close this issue.
